import { NextRequest, NextResponse } from 'next/server';
import { v2 as cloudinary } from 'cloudinary';

cloudinary.config({
    cloud_name: process.env.CLOUDINARY_CLOUD_NAME,
    api_key: process.env.CLOUDINARY_API_KEY,
    api_secret: process.env.CLOUDINARY_API_SECRET,
});

/**
 * Cloudinary cleanup cron — deletes old GENERATED/filled documents only.
 * 
 * ONLY targets: `filled-documents/` folder (generated by template fill flow)
 * NEVER touches: template source Word files, order files, or any other assets
 * 
 * Call via Vercel Cron or manually: GET /api/cron/cleanup-files
 * Protected by CRON_SECRET header check.
 */
export async function GET(request: NextRequest) {
    // Verify cron secret to prevent unauthorized access
    const authHeader = request.headers.get('authorization');
    const cronSecret = process.env.CRON_SECRET;

    if (cronSecret && authHeader !== `Bearer ${cronSecret}`) {
        return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    try {
        console.log('🧹 Starting Cloudinary cleanup for old filled documents...');

        // Only clean up files from the filled-documents folder
        // These are generated when users fill templates — safe to delete after 7 days
        const CLEANUP_FOLDER = 'filled-documents';
        const MAX_AGE_DAYS = 7;
        const cutoffDate = new Date(Date.now() - MAX_AGE_DAYS * 24 * 60 * 60 * 1000);
        const cutoffISO = cutoffDate.toISOString();

        let deletedCount = 0;
        let totalChecked = 0;
        let nextCursor: string | undefined;

        // Paginate through all resources in the filled-documents folder
        do {
            const result = await cloudinary.api.resources({
                type: 'upload',
                resource_type: 'raw',
                prefix: CLEANUP_FOLDER,
                max_results: 100,
                next_cursor: nextCursor,
            }) as { resources: Array<{ public_id: string; created_at: string }>; next_cursor?: string };

            nextCursor = result.next_cursor;

            for (const resource of result.resources) {
                totalChecked++;

                // Only delete files older than MAX_AGE_DAYS
                if (resource.created_at < cutoffISO) {
                    try {
                        await cloudinary.uploader.destroy(resource.public_id, { resource_type: 'raw' });
                        deletedCount++;
                        console.log(`🗑️ Deleted: ${resource.public_id} (created: ${resource.created_at})`);
                    } catch (deleteError) {
                        console.error(`❌ Failed to delete ${resource.public_id}:`, deleteError);
                    }
                }
            }
        } while (nextCursor);

        console.log(`🧹 Cleanup complete: checked ${totalChecked} files, deleted ${deletedCount} files older than ${MAX_AGE_DAYS} days`);

        return NextResponse.json({
            success: true,
            checked: totalChecked,
            deleted: deletedCount,
            maxAgeDays: MAX_AGE_DAYS,
            folder: CLEANUP_FOLDER,
        });
    } catch (error) {
        console.error('❌ Cloudinary cleanup error:', error);
        return NextResponse.json(
            { success: false, error: error instanceof Error ? error.message : 'Cleanup failed' },
            { status: 500 }
        );
    }
}
