import mongoose from 'mongoose';

export interface IOrder {
  _id: string;
  orderId: string;
  customerInfo: {
    name: string;
    phone: string;
    email: string;
  };
  orderType: 'file' | 'template';
  fileURL?: string;
  fileType?: string; // Store the original file type (e.g., 'application/pdf', 'image/jpeg')
  originalFileName?: string; // Store the original file name
  // Template-specific fields
  templateId?: string;
  templateName?: string;
  formData?: Record<string, string | number | boolean>;
  filledDocxUrl?: string;
  filledPdfUrl?: string;
  // Legacy template data for backward compatibility
  templateData?: {
    templateType: string;
    formData: Record<string, string | number | boolean>;
    generatedPDF?: string;
  };
  printingOptions: {
    pageSize: 'A4' | 'A3';
    color: 'color' | 'bw' | 'mixed';
    sided: 'single' | 'double';
    copies: number;
    pageCount?: number;
    serviceOption?: 'binding' | 'file' | 'service';
    pageColors?: {
      colorPages: number[]; // Array of page numbers that should be printed in color
      bwPages: number[];    // Array of page numbers that should be printed in B&W
    };
  };
  paymentStatus: 'pending' | 'completed' | 'failed';
  orderStatus: 'pending' | 'printing' | 'dispatched' | 'delivered';
  status?: 'pending_payment' | 'paid' | 'processing' | 'completed' | 'cancelled';
  amount: number;
  deliveryOption: {
    type: 'pickup' | 'delivery';
    location?: {
      lat: number;
      lng: number;
      address: string;
    };
    distance?: number;
    deliveryCharge?: number;
    address?: string;
    city?: string;
    pinCode?: string;
    pickupLocationId?: string;
  };
  razorpayOrderId?: string;
  razorpayPaymentId?: string;
  expectedDate?: Date;
  createdAt: Date;
  updatedAt: Date;
}

const orderSchema = new mongoose.Schema<IOrder>({
  orderId: {
    type: String,
    required: false, // Will be auto-generated by pre-save hook
    unique: true,
  },
  customerInfo: {
    name: { type: String, required: true },
    phone: { type: String, required: true },
    email: { type: String, required: true },
  },
  orderType: {
    type: String,
    enum: ['file', 'template'],
    required: true,
  },
  fileURL: String,
  fileType: String,
  originalFileName: String,
  // Template-specific fields
  templateId: String,
  templateName: String,
  formData: mongoose.Schema.Types.Mixed,
  filledDocxUrl: String,
  filledPdfUrl: String,
  // Legacy template data for backward compatibility
  templateData: {
    templateType: String,
    formData: mongoose.Schema.Types.Mixed,
    generatedPDF: String,
  },
  printingOptions: {
    pageSize: {
      type: String,
      enum: ['A4', 'A3'],
      required: true,
    },
    color: {
      type: String,
      enum: ['color', 'bw', 'mixed'],
      required: true,
    },
    sided: {
      type: String,
      enum: ['single', 'double'],
      required: true,
    },
    copies: {
      type: Number,
      required: true,
      min: 1,
    },
    pageCount: {
      type: Number,
      default: 1,
    },
    serviceOption: {
      type: String,
      enum: ['binding', 'file', 'service'],
    },
    pageColors: {
      colorPages: [Number], // Array of page numbers for color printing
      bwPages: [Number],    // Array of page numbers for B&W printing
    },
  },
  paymentStatus: {
    type: String,
    enum: ['pending', 'completed', 'failed'],
    default: 'pending',
  },
  orderStatus: {
    type: String,
    enum: ['pending', 'printing', 'dispatched', 'delivered'],
    default: 'pending',
  },
  status: {
    type: String,
    enum: ['pending_payment', 'paid', 'processing', 'completed', 'cancelled'],
    default: 'pending_payment',
  },
  amount: {
    type: Number,
    required: true,
  },
  deliveryOption: {
    type: {
      type: String,
      enum: ['pickup', 'delivery'],
      required: true,
      default: 'pickup'
    },
    pickupLocationId: String,
    location: {
      lat: Number,
      lng: Number,
      address: String
    },
    distance: Number,
    deliveryCharge: Number,
    address: String,
    city: String,
    pinCode: String
  },
  razorpayOrderId: String,
  razorpayPaymentId: String,
  expectedDate: {
    type: Date,
    validate: {
      validator: function(value: Date) {
        if (!value) return true; // Optional field
        const today = new Date();
        today.setHours(0, 0, 0, 0); // Reset time to start of day
        return value >= today; // Must be today or later
      },
      message: 'Expected delivery date must be today or later'
    }
  },
}, {
  timestamps: true,
});

// Generate order ID before saving
orderSchema.pre('save', async function(next) {
  if (this.isNew && !this.orderId) {
    let attempts = 0;
    const maxAttempts = 10;
    
    while (attempts < maxAttempts) {
      try {
        // Use timestamp + random number for better uniqueness
        const timestamp = Date.now().toString().slice(-6);
        const random = Math.floor(Math.random() * 1000).toString().padStart(3, '0');
        const candidateOrderId = `ORD${timestamp}${random}`;
        
        // Check if this orderId already exists
        const existingOrder = await mongoose.model('Order').findOne({ orderId: candidateOrderId });
        
        if (!existingOrder) {
          this.orderId = candidateOrderId;
          break;
        }
        
        attempts++;
      } catch (error) {
        console.error('Error generating order ID:', error);
        attempts++;
      }
    }
    
    // Fallback to UUID if all attempts fail
    if (!this.orderId) {
      const { v4: uuidv4 } = await import('uuid');
      this.orderId = `ORD${uuidv4().replace(/-/g, '').substring(0, 10).toUpperCase()}`;
    }
  }
  next();
});

export default mongoose.models.Order || mongoose.model<IOrder>('Order', orderSchema);
