import mongoose from 'mongoose';

export interface IOrder {
  _id: string;
  orderId: string;
  customerInfo: {
    name: string;
    phone: string;
    email: string;
  };
  orderType: 'file' | 'template';
  fileURL?: string; // Legacy: single file URL (for backward compatibility)
  fileURLs?: string[]; // Array of file URLs for multiple files
  fileType?: string; // Store the original file type (e.g., 'application/pdf', 'image/jpeg')
  originalFileName?: string; // Store the original file name
  originalFileNames?: string[]; // Array of original file names for multiple files
  // Template-specific fields
  templateId?: string;
  templateName?: string;
  formData?: Record<string, string | number | boolean>;
  filledDocxUrl?: string;
  filledPdfUrl?: string;
  // Legacy template data for backward compatibility
  templateData?: {
    templateType: string;
    formData: Record<string, string | number | boolean>;
    generatedPDF?: string;
  };
  printingOptions: {
    pageSize: 'A4' | 'A3';
    color: 'color' | 'bw' | 'mixed';
    sided: 'single' | 'double';
    copies: number;
    pageCount?: number;
    serviceOption?: 'binding' | 'file' | 'service'; // Legacy support
    serviceOptions?: ('binding' | 'file' | 'service')[]; // Per-file service options
    pageColors?: {
      colorPages: number[]; // Array of page numbers that should be printed in color
      bwPages: number[];    // Array of page numbers that should be printed in B&W
    } | Array<{ // Per-file page colors (new format)
      colorPages: number[]; // Array of page numbers that should be printed in color
      bwPages: number[];    // Array of page numbers that should be printed in B&W
    }>;
  };
  paymentStatus: 'pending' | 'completed' | 'failed';
  orderStatus: 'pending' | 'processing' | 'printing' | 'dispatched' | 'delivered';
  status: 'pending_payment' | 'paid' | 'processing' | 'printing' | 'dispatched' | 'delivered' | 'cancelled' | 'refunded';
  amount: number;
  deliveryOption: {
    type: 'pickup' | 'delivery';
    location?: {
      lat: number;
      lng: number;
      address: string;
    };
    distance?: number;
    deliveryCharge?: number;
    address?: string;
    city?: string;
    pinCode?: string;
    pickupLocationId?: string;
    pickupLocation?: {
      _id: string;
      name: string;
      address: string;
      lat: number;
      lng: number;
      contactPerson?: string;
      contactPhone?: string;
      operatingHours?: string;
      gmapLink?: string;
    };
  };
  razorpayOrderId?: string;
  razorpayPaymentId?: string;
  expectedDate?: Date;
  deliveryNumber?: string; // Format: {LETTER}{YYYYMMDD}{PRINTER_INDEX}
  createdAt: Date;
  updatedAt: Date;
}

const orderSchema = new mongoose.Schema<IOrder>({
  orderId: {
    type: String,
    required: false, // Will be auto-generated by pre-save hook
    unique: true,
    index: true,
  },
  customerInfo: {
    name: { type: String, required: true },
    phone: { type: String, required: true },
    email: { type: String, required: true },
  },
  orderType: {
    type: String,
    enum: ['file', 'template'],
    required: true,
  },
  fileURL: String, // Legacy: single file URL (for backward compatibility)
  fileURLs: [String], // Array of file URLs for multiple files
  fileType: String,
  originalFileName: String, // Legacy: single file name (for backward compatibility)
  originalFileNames: [String], // Array of original file names for multiple files
  // Template-specific fields
  templateId: String,
  templateName: String,
  formData: mongoose.Schema.Types.Mixed,
  filledDocxUrl: String,
  filledPdfUrl: String,
  // Legacy template data for backward compatibility
  templateData: {
    templateType: String,
    formData: mongoose.Schema.Types.Mixed,
    generatedPDF: String,
  },
  printingOptions: {
    pageSize: {
      type: String,
      enum: ['A4', 'A3'],
      required: true,
    },
    color: {
      type: String,
      enum: ['color', 'bw', 'mixed'],
      required: true,
    },
    sided: {
      type: String,
      enum: ['single', 'double'],
      required: true,
    },
    copies: {
      type: Number,
      required: true,
      min: 1,
    },
    pageCount: {
      type: Number,
      default: 1,
    },
    serviceOption: {
      type: String,
      enum: ['binding', 'file', 'service'],
    },
    serviceOptions: {
      type: [String],
      enum: ['binding', 'file', 'service'],
    },
    pageColors: {
      type: mongoose.Schema.Types.Mixed, // Support both single object and array format
      // Can be:
      // 1. Single object: { colorPages: [Number], bwPages: [Number] } (legacy)
      // 2. Array: [{ colorPages: [Number], bwPages: [Number] }, ...] (per-file)
    },
  },
  paymentStatus: {
    type: String,
    enum: ['pending', 'completed', 'failed'],
    default: 'pending',
  },
  orderStatus: {
    type: String,
    enum: ['pending', 'processing', 'printing', 'dispatched', 'delivered'],
    default: 'pending',
  },
  status: {
    type: String,
    enum: ['pending_payment', 'paid', 'processing', 'printing', 'dispatched', 'delivered', 'cancelled', 'refunded'],
    default: 'pending_payment',
  },
  amount: {
    type: Number,
    required: true,
  },
  deliveryOption: {
    type: {
      type: String,
      enum: ['pickup', 'delivery'],
      required: true,
      default: 'pickup'
    },
    pickupLocationId: String,
    pickupLocation: {
      _id: String,
      name: String,
      address: String,
      lat: Number,
      lng: Number,
      contactPerson: String,
      contactPhone: String,
      operatingHours: String,
      gmapLink: String
    },
    location: {
      lat: Number,
      lng: Number,
      address: String
    },
    distance: Number,
    deliveryCharge: Number,
    address: String,
    city: String,
    pinCode: String
  },
  razorpayOrderId: String,
  razorpayPaymentId: String,
  expectedDate: {
    type: Date,
    validate: {
      validator: function(value: Date) {
        if (!value) return true; // Optional field
        const today = new Date();
        today.setHours(0, 0, 0, 0); // Reset time to start of day
        return value >= today; // Must be today or later
      },
      message: 'Expected delivery date must be today or later'
    }
  },
  deliveryNumber: String, // Format: {LETTER}{YYYYMMDD}{PRINTER_INDEX}
}, {
  timestamps: true,
});

// Generate order ID before saving
orderSchema.pre('save', async function(next) {
  if (this.isNew && !this.orderId) {
    let attempts = 0;
    const maxAttempts = 10;
    
    while (attempts < maxAttempts) {
      try {
        // Use timestamp + random number for better uniqueness
        const timestamp = Date.now().toString().slice(-6);
        const random = Math.floor(Math.random() * 1000).toString().padStart(3, '0');
        const candidateOrderId = `ORD${timestamp}${random}`;
        
        // Check if this orderId already exists
        const existingOrder = await mongoose.model('Order').findOne({ orderId: candidateOrderId });
        
        if (!existingOrder) {
          this.orderId = candidateOrderId;
          break;
        }
        
        attempts++;
      } catch (error) {
        console.error('Error generating order ID:', error);
        attempts++;
      }
    }
    
    // Fallback to UUID if all attempts fail
    if (!this.orderId) {
      const { v4: uuidv4 } = await import('uuid');
      this.orderId = `ORD${uuidv4().replace(/-/g, '').substring(0, 10).toUpperCase()}`;
    }
  }
  next();
});

export default mongoose.models.Order || mongoose.model<IOrder>('Order', orderSchema);
